framework:
    cache:
        default_redis_provider: '%env(REDIS_HOST)%'
        pools:
            ip_address_info.cache:
                adapter: cache.adapter.redis
                default_lifetime: '%env(REDIS_LIFETIME_IN_SECONDS)%'